name: "Vail Monitor"
description: "Monitors CW activity on https://vail.woozle.org"
version: "1.0.1"
slug: "vail"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  Notify via Telegram: true
  Vail channel: "YO3AX"
  Telegram bot token: "LaLaLa"
  Telegram recipient: "someone"
schema:
  Notify via Telegram: bool
  Vail channel: str
  Telegram bot token: str
