name: "Vail Monitor"
description: "[WIP] https://vail.woozle.org monitor"
version: "1.0.4"
slug: "vail"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  Notify via Telegram: true
  Vail channel: "enter the Vail channel name that will be monitored by the addon. (Example: YO3AX to monitor https://vail.woozle.org/#YO3AX)"
  Telegram bot token: "enter token of telegram bot that will be used to send notifications"
  Telegram recipient: "enter id of recipient telegram channel / contact that will receive the notifications"
schema:
  Notify via Telegram: bool
  Vail channel: str
  Telegram bot token: str
  Telegram recipient: str
